# Dataset paths.
TSIRMT:
  train_seqs_file:  /root/SGMP_Unet/Datasets/TSIRMT/train_new.txt
  val_seqs_file:  /root/SGMP_Unet/Datasets/TSIRMT/val_new.txt
  img_path: /root/autodl-tmp/TSIRMT/images
  mask_path: /root/autodl-tmp/TSIRMT/masks

NUDT-MIRSDT:
  train_seqs_file: /root/SGMP_Unet/Datasets/NUDT-MIRSDT/train_new.txt
  val_seqs_file: /root/SGMP_Unet/Datasets/NUDT-MIRSDT/val_new.txt

IRDST:
  train_seqs_file: /root/SGMP_Unet/Datasets/IRDST/train_new.txt
  val_seqs_file: /root/SGMP_Unet/Datasets/IRDST/val_new.txt

TSIRMT_tiny:
  train_seqs_file: /root/SGMP_Unet/Datasets/TSIRMT_tiny/train_new.txt
  val_seqs_file: /root/SGMP_Unet/Datasets/TSIRMT_tiny/val_new.txt
  img_path: /root/autodl-tmp/TSIRMT_tiny/images
  mask_path: /root/autodl-tmp/TSIRMT_tiny/masks


