# Dataset paths.
TSIRMT:
  train_seqs_file:  /home/mc/zhangwei/Project/SGMP_Unet/Datasets/TSIRMT/train_new.txt
  val_seqs_file:  /home/mc/zhangwei/Project/SGMP_Unet/Datasets/TSIRMT/val_new.txt
  img_path: /home/mc/zhangwei/IRDST_Dataset/TSIRMT/images
  mask_path: /home/mc/zhangwei/IRDST_Dataset/TSIRMT/masks

NUDT-MIRSDT:
  train_seqs_file: /home/mc/zhangwei/Project/SGMP_Unet/Datasets/NUDT-MIRSDT/train_new.txt
  val_seqs_file: /home/mc/zhangwei/Project/SGMP_Unet/Datasets/NUDT-MIRSDT/val_new.txt
  img_path: /home/mc/zhangwei/IRDST_Dataset/NUDT-MIRSDT/images
  mask_path: /home/mc/zhangwei/IRDST_Dataset/NUDT-MIRSDT/masks

IRDST:
  train_seqs_file: /home/mc/zhangwei/Project/SGMP_Unet/Datasets/IRDST/train_new.txt
  val_seqs_file: /home/mc/zhangwei/Project/SGMP_Unet/Datasets/IRDST/val_new.txt
  img_path: /home/mc/zhangwei/IRDST_Dataset/IRDST/images
  mask_path: /home/mc/zhangwei/IRDST_Dataset/IRDST/masks


